on:
  push:
    branches: [main]
  pull_request:
name: Test
permissions:
  contents: read
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.23.x, 1.24.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
        shell: bash
      - name: Install golint
        run: go install golang.org/x/lint/golint@latest
        shell: bash
      - name: Update PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        shell: bash
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Fmt
        if: matrix.platform != 'windows-latest' # :(
        run: "diff <(gofmt -d .) <(printf '')"
        shell: bash
      - name: Vet
        run: go vet ./...
      - name: Staticcheck
        run: staticcheck ./...
      - name: Lint
        run: golint ./...
      - name: Test
        run: go test -race ./...
